name: Analyze with CodeGuru Reviewer

on:
  - push
  - workflow_dispatch # This allows manual triggering of the action through the GitHub UI.

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  build:
    name: Analyze with CodeGuru Reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2


      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build project
        run: mvn compile -DskipTests

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        continue-on-error: false
        with:
          build_path: target
          s3_bucket: codeguru-reviewer-serverest-caio


      - name: Store SARIF file
        uses: actions/upload-artifact@v4
        with:
          name: SARIF_recommendations
          path: ./codeguru-results.sarif.json

      - name: Upload review result
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json