name: aws
on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]

jobs:
  AWS:
    runs-on: ubuntu-latest
    name: aws
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          github_token: ${{ github.token }}

      - name: Test AWS Credentials
        run: |
            aws sts get-caller-identity

      - name: Ensure S3 Bucket Exists
        run: |
          BUCKET_NAME="codeguru-reviewer-serverest-caio"
          if ! aws s3 ls "s3://$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket does not exist, creating..."
            aws s3 mb "s3://$BUCKET_NAME" --region us-west-2
          else
            echo "Bucket exists."
          fi

      - name: Check for Existing CodeGuru Association
        id: check_association
        run: |
                ASSOCIATION_ARN=$(aws codeguru-reviewer list-repository-associations --query "RepositoryAssociationSummaries[?Name=='ServeRest-Actions'].AssociationArn" --output text)
                if [[ -n "$ASSOCIATION_ARN" ]]; then
                  echo "Found existing association: $ASSOCIATION_ARN"
                  echo "ASSOCIATION_ARN=$ASSOCIATION_ARN" >> $GITHUB_ENV
                else
                  echo "No existing association found."
                fi

      - name: Remove Failed Association (if exists)
        if: env.ASSOCIATION_ARN != ''
        run: |
                echo "Removing failed CodeGuru association..."
                aws codeguru-reviewer disassociate-repository --association-arn $ASSOCIATION_ARN

      - name: Reassociate Repository with CodeGuru
        run: |
                aws codeguru-reviewer associate-repository --repository Name="ServeRest-Actions",Type="GITHUB"

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          build_path: target
          s3_bucket: codeguru-reviewer-serverest-caio

      - name: Upload review result
        if: ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json